import type { DbGameStateRow } from './repo.js';
import type { CeremonyReport } from '@mls/shared/game-types';

interface CeremonyNpc {
  name: string;
  division: string;
  unit: string;
  position: string;
  competenceScore: number;
}

const FIRST_NAMES = ['James', 'Michael', 'William', 'David', 'Joseph', 'Daniel', 'Matthew', 'Anthony', 'Andrew', 'Christopher', 'Robert', 'Thomas'];
const LAST_NAMES = ['Anderson', 'Walker', 'Rodriguez', 'Bennett', 'Parker', 'Morgan', 'Hughes', 'Cooper', 'Price', 'Foster', 'Sullivan', 'Reed'];
const DIVISIONS = ['Infantry Division', 'Naval Operations', 'Logistics Command', 'Signals & Cyber'];
const UNITS = ['1st Brigade', '2nd Fleet Group', 'Joint Recon Unit', 'Medical Support Unit', 'Rapid Response Group'];
const POSITIONS = ['Division Commander', 'Deputy Commander', 'Operations Officer', 'Training Officer', 'Unit Sergeant Major'];
const MEDALS = ['Distinguished Service Medal', 'Meritorious Service Medal', 'Combat Readiness Medal', 'Joint Commendation Medal', 'Leadership Ribbon'];

function seededValue(day: number, idx: number, salt: number) {
  return Math.abs((day + 3) * 97 + idx * 37 + salt * 19);
}

function pick<T>(arr: T[], seed: number): T {
  return arr[seed % arr.length] as T;
}

function buildNpc(day: number, idx: number): CeremonyNpc {
  const base = seededValue(day, idx, 1);
  const growth = (day * ((idx % 4) + 2)) / 6;
  return {
    name: `${pick(FIRST_NAMES, base)} ${pick(LAST_NAMES, seededValue(day, idx, 2))}`,
    division: pick(DIVISIONS, seededValue(day, idx, 3)),
    unit: pick(UNITS, seededValue(day, idx, 4)),
    position: pick(POSITIONS, seededValue(day, idx, 5)),
    competenceScore: Math.round(40 + (base % 35) + growth)
  };
}

function buildNpcPool(day: number): CeremonyNpc[] {
  return Array.from({ length: 22 }, (_, idx) => buildNpc(day, idx)).sort((a, b) => b.competenceScore - a.competenceScore);
}

function ceremonyDay(gameDay: number): number {
  if (gameDay < 12) return 12;
  return Math.floor(gameDay / 12) * 12;
}

export function buildCeremonyReport(state: DbGameStateRow): CeremonyReport {
  const currentCeremonyDay = ceremonyDay(state.current_day);
  const previousCeremonyDay = Math.max(12, currentCeremonyDay - 12);
  const npcPool = buildNpcPool(currentCeremonyDay);
  const previousPool = buildNpcPool(previousCeremonyDay);

  const chief = npcPool[0];
  const previousChief = previousPool[0];
  const quota = Math.max(2, Math.min(8, Math.round(chief.competenceScore / 22 + state.morale / 28)));
  const recipients = npcPool.slice(1, quota + 1).map((npc, idx) => ({
    order: idx + 1,
    npcName: npc.name,
    division: npc.division,
    unit: npc.unit,
    position: npc.position,
    medalName: MEDALS[idx % MEDALS.length],
    ribbonName: `Ribbon-${(idx % 5) + 1}`,
    reason: `Performance score ${npc.competenceScore} with sustained readiness and leadership impact.`
  }));

  const logs = [
    `Ceremony starts on Day ${currentCeremonyDay}. All personnel are assembled for formation and readiness brief.`,
    `Chief of Staff ${chief.name} opens the ceremony and confirms medal quota (${quota}) generated by command AI.`,
    'Medal ribbon session is executed sequentially, one recipient at a time, with live command log updates.',
    'Ceremony closes with branch-wide directives for next 12-day operational cycle.'
  ];

  return {
    ceremonyDay: currentCeremonyDay,
    attendance: npcPool.length + 1,
    medalQuota: quota,
    chiefOfStaff: {
      name: chief.name,
      competenceScore: chief.competenceScore,
      previousChiefName: previousChief?.name ?? null,
      replacedPreviousChief: Boolean(previousChief && previousChief.name !== chief.name)
    },
    logs,
    recipients
  };
}
