ALTER TABLE game_states
  ADD COLUMN IF NOT EXISTS player_division TEXT NOT NULL DEFAULT 'General Command',
  ADD COLUMN IF NOT EXISTS national_stability INTEGER NOT NULL DEFAULT 72,
  ADD COLUMN IF NOT EXISTS military_stability INTEGER NOT NULL DEFAULT 70,
  ADD COLUMN IF NOT EXISTS military_fund_cents INTEGER NOT NULL DEFAULT 250000,
  ADD COLUMN IF NOT EXISTS fund_secretary_npc TEXT,
  ADD COLUMN IF NOT EXISTS corruption_risk INTEGER NOT NULL DEFAULT 18,
  ADD COLUMN IF NOT EXISTS court_pending_cases JSONB NOT NULL DEFAULT '[]'::jsonb;
